const { VITE_BACKEND_URL, MODE, PROD,VITE_FRONTEND_URL } = import.meta.env;

export const FRONTEND_ENVS = {
  BACKEND_URL: VITE_BACKEND_URL,
  FRONTEND_URL: VITE_FRONTEND_URL,
  MODE: MODE,
  PROD: PROD,
};
